repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        pass_filenames: false
        args:
          - --fix
          - power_sdk/contracts
          - power_sdk/schemas
          - power_sdk/devices
      - id: ruff-format
        pass_filenames: false
        args:
          - power_sdk/contracts
          - power_sdk/schemas
          - power_sdk/devices

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - --config-file=pyproject.toml
          - power_sdk/contracts
          - power_sdk/schemas
          - power_sdk/devices
        additional_dependencies:
          - types-setuptools

